import { build, transform } from "esbuild";
import { createHash } from "node:crypto";
import { gzipSync, gunzipSync } from "node:zlib";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(root, "src");
const output = path.join(root, ".build");
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

const jsResult = await build({
  entryPoints: [path.join(source, "app.js")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["safari15", "chrome100", "firefox100"],
  minify: true,
  charset: "utf8",
  legalComments: "none",
  define: {
    __APP_VERSION__: JSON.stringify(packageJson.version),
    __MESHCORE_JS_VERSION__: JSON.stringify(packageJson.dependencies["@liamcottle/meshcore.js"]),
  },
});
const cssResult = await transform(await readFile(path.join(source, "styles.css"), "utf8"), {
  loader: "css",
  minify: true,
});

const template = await readFile(path.join(source, "index.html"), "utf8");
const html = template
  .replace("/*__RCC6_CSS__*/", cssResult.code.trim())
  .replace("/*__RCC6_JS__*/", jsResult.outputFiles[0].text.trim());

if (html.includes("/*__RCC6_")) throw new Error("Unreplaced WebUI build token");
if (/<script\s+[^>]*src=|<link\s+[^>]*rel=[\"']stylesheet/i.test(html)) {
  throw new Error("Runtime network asset reference detected");
}

const gzip = gzipSync(Buffer.from(html), { level: 9, mtime: 0 });
gzip[9] = 0xff; // RFC 1952 OS=unknown keeps the asset identical across build hosts.
if (gunzipSync(gzip).toString("utf8") !== html) throw new Error("Gzip round-trip failed");
const digest = createHash("sha256").update(gzip).digest("hex");
const rows = [];
for (let offset = 0; offset < gzip.length; offset += 16) {
  rows.push(`  ${[...gzip.subarray(offset, offset + 16)].map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
}

const header = `// Generated by examples/companion_radio/webui/build.mjs. Do not edit.\n// gzip sha256: ${digest}\n#pragma once\n#include <Arduino.h>\n\nextern const uint8_t RCC6_WEB_UI_INDEX_GZ[] PROGMEM;\nextern const size_t RCC6_WEB_UI_INDEX_GZ_LEN;\n\n#ifdef RCC6_WEB_UI_ASSETS_IMPLEMENTATION\nconst uint8_t RCC6_WEB_UI_INDEX_GZ[] PROGMEM = {\n${rows.join("\n")}\n};\nconst size_t RCC6_WEB_UI_INDEX_GZ_LEN = sizeof(RCC6_WEB_UI_INDEX_GZ);\n#endif\n`;

await mkdir(output, { recursive: true });
await writeFile(path.join(output, "index.html"), html);
await writeFile(path.join(output, "index.html.gz"), gzip);
await writeFile(path.join(root, "Rcc6WebUiAssets.h"), header);
console.log(`RCC6 WebUI: ${Buffer.byteLength(html)} bytes HTML, ${gzip.length} bytes gzip, sha256 ${digest}`);
